"use strict";
const $=id=>document.getElementById(id);
function setStatus(message,type=""){const e=$("status");e.textContent=message;e.className="status "+type;}
function splitText(text,limit=2400){const clean=text.replace(/\r/g,"").trim();if(!clean)return[];const sentences=clean.match(/[^.!?।]+[.!?।]+|[^.!?।]+$/g)||[clean];const chunks=[];let cur="";for(const sentence of sentences){const s=sentence.trim();if(!s)continue;if(cur&&(cur.length+1+s.length)>limit){chunks.push(cur.trim());cur=""}if(s.length<=limit){cur+=(cur?" ":"")+s;continue}for(const word of s.split(/\s+/)){if(!cur)cur=word;else if(cur.length+1+word.length<=limit)cur+=" "+word;else{chunks.push(cur.trim());cur=word}}}if(cur.trim())chunks.push(cur.trim());return chunks}
function b64ToBytes(b64){const bin=atob(b64);const out=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)out[i]=bin.charCodeAt(i);return out}
function ascii(b,o,n){return String.fromCharCode(...b.slice(o,o+n))}function u32(b,o){return new DataView(b.buffer,b.byteOffset,b.byteLength).getUint32(o,true)}function u16(b,o){return new DataView(b.buffer,b.byteOffset,b.byteLength).getUint16(o,true)}
function parseWav(bytes){if(ascii(bytes,0,4)!=="RIFF"||ascii(bytes,8,4)!=="WAVE")throw Error("Sarvam returned an unsupported WAV file.");let p=12,fmt=null,data=null;while(p+8<=bytes.length){const id=ascii(bytes,p,4),size=u32(bytes,p+4),start=p+8;if(id==="fmt ")fmt={audioFormat:u16(bytes,start),channels:u16(bytes,start+2),sampleRate:u32(bytes,start+4),byteRate:u32(bytes,start+8),blockAlign:u16(bytes,start+12),bitsPerSample:u16(bytes,start+14)};else if(id==="data")data=bytes.slice(start,start+size);p=start+size+(size%2)}if(!fmt||!data)throw Error("Invalid WAV structure.");return{fmt,data}}
function makeWav(fmt,pcm){const h=new ArrayBuffer(44),v=new DataView(h);const w=(o,t)=>{for(let i=0;i<t.length;i++)v.setUint8(o+i,t.charCodeAt(i))};w(0,"RIFF");v.setUint32(4,36+pcm.length,true);w(8,"WAVE");w(12,"fmt ");v.setUint32(16,16,true);v.setUint16(20,fmt.audioFormat,true);v.setUint16(22,fmt.channels,true);v.setUint32(24,fmt.sampleRate,true);v.setUint32(28,fmt.byteRate,true);v.setUint16(32,fmt.blockAlign,true);v.setUint16(34,fmt.bitsPerSample,true);w(36,"data");v.setUint32(40,pcm.length,true);return new Blob([h,pcm],{type:"audio/wav"})}
function mergeWavs(parts){const parsed=parts.map(x=>parseWav(b64ToBytes(x))),f=parsed[0].fmt;for(const x of parsed){const a=x.fmt;if(a.audioFormat!==f.audioFormat||a.channels!==f.channels||a.sampleRate!==f.sampleRate||a.bitsPerSample!==f.bitsPerSample)throw Error("Audio format changed between parts; cannot safely merge.")}const total=parsed.reduce((n,x)=>n+x.data.length,0),pcm=new Uint8Array(total);let o=0;for(const x of parsed){pcm.set(x.data,o);o+=x.data.length}return makeWav(f,pcm)}
async function generateVoiceover(){const text=$("script").value.trim();if(!text){setStatus("Please paste your script first.","error");return}const chunks=splitText(text,2400),btn=$("generate");btn.disabled=true;btn.textContent="Generating...";$("download").hidden=true;$("audio").hidden=true;$("parts").textContent=`Preparing ${chunks.length} part(s)...`;try{const audios=[];for(let i=0;i<chunks.length;i++){setStatus(`Generating voiceover part ${i+1} of ${chunks.length}...`);const r=await fetch("/api/tts",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({text:chunks[i],language_code:$("language").value,speaker:$("speaker").value,pace:Number($("pace").value)})});const d=await r.json();if(!r.ok)throw Error(d.error||`Part ${i+1} failed.`);audios.push(d.audio);$("parts").textContent=`Completed ${i+1} of ${chunks.length} part(s).`}setStatus("All parts generated. Joining the audio...");const blob=mergeWavs(audios),url=URL.createObjectURL(blob);$("audio").src=url;$("audio").hidden=false;$("download").href=url;$("download").download="VANTARA-Voiceover.wav";$("download").textContent="⬇ Download VANTARA Voiceover";$("download").hidden=false;setStatus("Voiceover completed. Your downloadable WAV file is ready.","success");$("parts").textContent=`${chunks.length} part(s) generated and merged into one file.`}catch(e){console.error(e);setStatus(e.message||"Voiceover generation failed.","error")}finally{btn.disabled=false;btn.textContent="Generate Real Voiceover"}}
$("generate").addEventListener("click",generateVoiceover);
